from __future__ import annotations
from typing import Protocol, Iterable

class RegistryAdapter(Protocol):
    def resolve_production(self, production_id:str)->dict: ...
    def list_due_predictions(self, as_of:str)->Iterable[dict]: ...
    def append_evaluation(self, evaluation:dict)->None: ...
    def update_health(self, production_id:str, health:dict)->None: ...

class MarketDataAdapter(Protocol):
    def get_actual(self, prediction:dict)->dict: ...
    def get_data_snapshot(self, task_id:str, as_of:str)->dict: ...

class LedgerAdapter(Protocol):
    def append_prediction(self, locked_prediction:dict)->None: ...
    def verify_prediction(self, prediction_id:str)->bool: ...
